Add dotenv module to manage environment variables

diff --git a/.github/workflows/pr-run.yaml b/.github/workflows/pr-run.yaml
--- a/.github/workflows/pr-run.yaml
+++ b/.github/workflows/pr-run.yaml
@@ -76,7 +76,18 @@ jobs:
       run: |
         # Retrieve the service name
         SERVICE_NAME=$(kubectl get services | grep 'deel-task-helm' | awk '{print $1}')
-        helm upgrade --install reverse-ips ./deel-task-helm --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }},\
-        image.tag=latest,environment.DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@$SERVICE_NAME:5432/${{ secrets.POSTGRES_DB }}
-
-
+    
+        # Error handling
+        if [ -z "$SERVICE_NAME" ];
+        then
+          echo "Service 'deel-task-helm' is not found";
+          exit 1;
+        fi
+    
+        # Build Image Information
+        IMAGE_INFO="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:latest"
+        DATABASE_INFO="postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@$SERVICE_NAME:5432/${{ secrets.POSTGRES_DB }}"
+    
+        # Run helm upgrade
+        helm upgrade --install reverse-ips ./deel-task-helm --set image.repository=$IMAGE_INFO,\
+        environment.DATABASE_URL=$DATABASE_INFO
